apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v3ien80lq-python
  janus-idp.io/tekton: v3ien80lq-python
  backstage.io/kubernetes-id: v3ien80lq-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: v3ien80lq-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
